// @ts-nocheck -- skip type checking
import * as docs_5 from "../content/docs/(getting-started)/index.mdx?collection=docs&hash=1750555234000"
import * as docs_4 from "../content/docs/writeups.mdx?collection=docs&hash=1750555234000"
import * as docs_3 from "../content/docs/reconnaissance.mdx?collection=docs&hash=1750555234000"
import * as docs_2 from "../content/docs/extensions.mdx?collection=docs&hash=1750555234000"
import * as docs_1 from "../content/docs/bug-hunting-toolkit.mdx?collection=docs&hash=1750555234000"
import * as docs_0 from "../content/docs/arsenal.mdx?collection=docs&hash=1750555234000"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"arsenal.mdx","absolutePath":"/home/krish/Documents/Develop/Penquin/Next js/content/docs/arsenal.mdx"}, data: docs_0 }, { info: {"path":"bug-hunting-toolkit.mdx","absolutePath":"/home/krish/Documents/Develop/Penquin/Next js/content/docs/bug-hunting-toolkit.mdx"}, data: docs_1 }, { info: {"path":"extensions.mdx","absolutePath":"/home/krish/Documents/Develop/Penquin/Next js/content/docs/extensions.mdx"}, data: docs_2 }, { info: {"path":"reconnaissance.mdx","absolutePath":"/home/krish/Documents/Develop/Penquin/Next js/content/docs/reconnaissance.mdx"}, data: docs_3 }, { info: {"path":"writeups.mdx","absolutePath":"/home/krish/Documents/Develop/Penquin/Next js/content/docs/writeups.mdx"}, data: docs_4 }, { info: {"path":"(getting-started)/index.mdx","absolutePath":"/home/krish/Documents/Develop/Penquin/Next js/content/docs/(getting-started)/index.mdx"}, data: docs_5 }], [{"info":{"path":"meta.json","absolutePath":"/home/krish/Documents/Develop/Penquin/Next js/content/docs/meta.json"},"data":{"title":"Penqiun","pages":["---LAUNCHPAD---","...(getting-started)","---BUG HUNTER'S ARMORY---","...arsenal","reconnaissance","methodology","extensions","writeups"],"description":"Docs for Hackers"}}, {"info":{"path":"(getting-started)/meta.json","absolutePath":"/home/krish/Documents/Develop/Penquin/Next js/content/docs/(getting-started)/meta.json"},"data":{"title":"Getting Started","pages":["index"]}}])