// @ts-nocheck -- skip type checking
import * as docs_6 from "../content/docs/(getting-started)/index.mdx?collection=docs&hash=1758385530000"
import * as docs_5 from "../content/docs/writeups.mdx?collection=docs&hash=1758385530000"
import * as docs_4 from "../content/docs/reconnaissance.mdx?collection=docs&hash=1758385530000"
import * as docs_3 from "../content/docs/methodology.mdx?collection=docs&hash=1758385530000"
import * as docs_2 from "../content/docs/extensions.mdx?collection=docs&hash=1758385530000"
import * as docs_1 from "../content/docs/bug-hunting-toolkit.mdx?collection=docs&hash=1758385530000"
import * as docs_0 from "../content/docs/arsenal.mdx?collection=docs&hash=1758385530000"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"arsenal.mdx","absolutePath":"X:/Develop/Codes/Penquin-V1/content/docs/arsenal.mdx"}, data: docs_0 }, { info: {"path":"bug-hunting-toolkit.mdx","absolutePath":"X:/Develop/Codes/Penquin-V1/content/docs/bug-hunting-toolkit.mdx"}, data: docs_1 }, { info: {"path":"extensions.mdx","absolutePath":"X:/Develop/Codes/Penquin-V1/content/docs/extensions.mdx"}, data: docs_2 }, { info: {"path":"methodology.mdx","absolutePath":"X:/Develop/Codes/Penquin-V1/content/docs/methodology.mdx"}, data: docs_3 }, { info: {"path":"reconnaissance.mdx","absolutePath":"X:/Develop/Codes/Penquin-V1/content/docs/reconnaissance.mdx"}, data: docs_4 }, { info: {"path":"writeups.mdx","absolutePath":"X:/Develop/Codes/Penquin-V1/content/docs/writeups.mdx"}, data: docs_5 }, { info: {"path":"(getting-started)\\index.mdx","absolutePath":"X:/Develop/Codes/Penquin-V1/content/docs/(getting-started)/index.mdx"}, data: docs_6 }], [{"info":{"path":"meta.json","absolutePath":"X:/Develop/Codes/Penquin-V1/content/docs/meta.json"},"data":{"title":"Penqiun","pages":["---Launchpad---","...(getting-started)","---Bug Hunter's Armory---","...arsenal","reconnaissance","methodology","extensions","writeups"],"description":"Docs for Hackers"}}, {"info":{"path":"(getting-started)\\meta.json","absolutePath":"X:/Develop/Codes/Penquin-V1/content/docs/(getting-started)/meta.json"},"data":{"title":"Getting Started","pages":["index"]}}])